usage: update.py [-h] [--enable-libopencore-amr] [--enable-libx264]
                 [--enable-libx265] [--enable-libogg] [--enable-libopus]
                 [--enable-libvorbis] [--enable-libtheora] [--enable-libvpx]
                 [--enable-libmp3lame] [--enable-libxvid]
                 [--enable-libfdk-aac] [--enable-libopenjpeg]
                 [--enable-libfreetype] [--enable-libvidstab]
                 [--enable-libfribidi] [--enable-libfontconfig]
                 [--enable-libass] [--enable-libkvazaar] [--enable-libaom]
                 [--enable-vaapi] [--enable-nvenc] [--enable-libdav1d]
                 [--enable-vdpau] [--enable-all] [--with-bins] [--no-strip]
                 [--fat | --slim | --scratch]
                 {alpine,centos,ubuntu,nvidia,armv7}
                 {snapshot,4.1,4.0,3.4,3.3,3.2,2.8}
update.py: error: argument variant: invalid choice: 'nvidia,' (choose from 'alpine', 'centos', 'ubuntu', 'nvidia', 'armv7')
