FFMPEG_VERSION=%%FFMPEG_VERSION%% \
    KVAZAAR_VERSION=2.3.1 \
    LIBVMAF_VERSION=3.0.0

## opencore-amr - https://sourceforge.net/projects/opencore-amr/
##         x264 - http://www.videolan.org/developers/x264.html
##         x265 - http://x265.org/ ( videolan )
##       libogg - https://www.xiph.org/ogg/ ( xiph )
##      libopus - https://www.opus-codec.org/ ( xiph )
##              - https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu#libopus
##    libvorbis - https://xiph.org/vorbis/ ( xiph )
##       libvpx - https://www.webmproject.org/code/
##              - https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu#libvpx
##      libwebp - https://developers.google.com/speed/webp/
##   libmp3lame - http://lame.sourceforge.net/
##         xvid - https://www.xvid.com/ (xvidcore)
##      fdk-aac - https://github.com/mstorsjo/fdk-aac
##              - https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu#libfdk-aac
##     openjpeg - https://github.com/uclouvain/openjpeg
##     freetype - https://www.freetype.org/
##                consider passing --no-install-recommends for this one its globbie (if you do, pass in libfreetype6)
##   libvidstab - https://github.com/georgmartius/vid.stab
##      fridibi - https://www.fribidi.org/
##   fontconfig - https://www.freedesktop.org/wiki/Software/fontconfig/
##       libass - https://github.com/libass/libass
##      lib aom - https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu#libaom
##    libsvtav1 - https://gitlab.com/AOMediaCodec/SVT-AV1.git
##              - https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu#libsvtav1
##     libdav1d - https://code.videolan.org/videolan/dav1d
##              - https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu#libdav1d
##  util-macros - (x.org) (and supporting libraries) for screen capture https://xcb.freedesktop.org/
##       xproto - (x.org)
##       libXau - 
##   libpthread - libpthread-stubs
##      libxml2 - for libbluray
##    libbluray - Requires libxml, freetype, and fontconfig
##       libzmq - https://github.com/zeromq/libzmq/
##                this one pulls in a bunch of dependencies
##       libpng - this one also pulls in a bunch of stuff
##   libaribb24 - 
##         zimg - https://github.com/sekrit-twc/zimg
##    libtheora - http://www.theora.org/ ( xiph )
##              - https://stackoverflow.com/questions/4810996/how-to-resolve-configure-guessing-build-type-failure
##       libsrt - https://github.com/Haivision/srt
##                Secure Reliable Transport UDP streaming library
##                multiple flavors (OpenSSL flavour) and ( GnuTLS flavour)
ARG OPENCORE_PKGS="libopencore-amrnb-dev libopencore-amrwb-dev"
ARG X264_PKGS="libx264-dev"
ARG X265_PKGS="libx265-dev libnuma-dev"
ARG OGG_PKGS="libogg-dev"
ARG OPUS_PKGS="libopus-dev"
ARG VORBIS_PKGS="libvorbis-dev"
ARG VPX_PKGS="libvpx-dev"
ARG WEBP_PKGS="libwebp-dev"
ARG MP3LAME_PKGS="libmp3lame-dev"
ARG XVIDCORE_PKGS="libxvidcore-dev"
ARG FDKAAC_PKGS="libfdk-aac-dev"
ARG OPENJP_PKGS="libopenjp2-7-dev"
ARG FREETYPE_PKGS="libfreetype6-dev"
ARG VIDSTAB_PKGS="libvidstab-dev"
ARG FRIBIDI_PKGS="libfribidi-dev"
ARG FONTCONFIG_PKGS="libfontconfig-dev fontconfig-config"
ARG LIBASS_PKGS="libass-dev"
ARG AOM_PKGS="libaom-dev"
ARG SVTAV1_PKGS="libsvtav1-dev libsvtav1enc-dev libsvtav1dec-dev"
ARG DAV1D_PKGS="libdav1d-dev"
ARG XORG_MACROS_PKGS="libxcb1-dev libxcb-shm0-dev libxcb-xfixes0-dev"
ARG XPROTO_PKGS="x11proto-core-dev"
ARG XAU_PKGS="libxau-dev"
ARG PTHREAS_STUBS_PKGS="libpthread-stubs0-dev"
ARG XML2_PKGS="libxml2-dev"
ARG BLURAY_PKGS="libbluray-dev"
ARG ZMQ_PKGS="libzmq3-dev"
ARG PNG_PKGS="libpng-dev"
ARG ARIBB24_PKGS="libaribb24-dev"
ARG ZIMG_PKGS="libzimg-dev"
ARG THEORA_PKGS="libtheora-dev"
ARG SRT_PKGS="libssl-dev libsrt-openssl-dev"
ARG LIBDRM_PKGS="libdrm-dev libdrm2 libxcb1-dev libxcb1"

ARG MAKEFLAGS="-j2"
ARG PKG_CONFIG_PATH="/opt/ffmpeg/share/pkgconfig:/opt/ffmpeg/lib/pkgconfig:/opt/ffmpeg/lib/x86_64-linux-gnu/pkgconfig:/opt/ffmpeg/lib64/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig"

ARG PREFIX="/opt/ffmpeg"
ARG LD_LIBRARY_PATH="/opt/ffmpeg/lib:/opt/ffmpeg/lib64"
