# Note: pass '--library-list lib1,lib2,lib3 for more control.
#       Here we have 3 libs that we have to build from source
RUN \
        /tmp/workdir/generate-source-of-truth-ffmpeg-versions.py

## when  debugging you can pass in || true to the end of the next 3 commands
## to keep the build going even if one of the steps fails
RUN \
        /tmp/workdir/download_tarballs.sh || true

RUN \
        /tmp/workdir/build_source.sh || true

RUN \
        /tmp/workdir/install_ffmpeg.sh || true
